version: '3.1'

services:
  php:
    build: ./
    ports:
      - 8881:80

  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1



 # docker-compose build
 #  # команда 1
 # 
 # docker-compose up
 #  # команда 2 запуск
